# These settings are synced to GitHub by https://probot.github.io/apps/settings/

_extends: .github

repository:
  name: MenuBundle
  description: This bundle provides services for defining static menus for sonata.
  homepage: https://core23.de
  topics: symfony, symfony-bundle, bundle, php, menu, knpmenu, generator, sonata, sonata-block

branches:
  - name: master
    protection:
      enforce_admins: false
      required_status_checks:
        contexts:
          - "Coding Standards (7.4)"
          - "Static Code Analysis (7.4)"
          - "Tests (7.3, lowest)"
          - "Tests (7.3, highest)"
          - "Tests (7.4, lowest)"
          - "Tests (7.4, highest)"
          - "Code Coverage (7.4)"
          - "Mutation Tests (7.4)"
        strict: true

      required_pull_request_reviews: null
      restrictions: null
